### ISSUE TITLE
Get a UTF-8 string?

### ISSUE THREAD

**Issue by jmarshall9120** [cocagne/pysrp#54]
I'm trying to use this library to do SRP for AWS cognito.  I need to pass everything to the API as UTF-8 string.  I've noticed its all encoded this way:

```python
def long_to_bytes(n):
    l = list()
    x = 0
    off = 0
    while x != n:
        b = (n >> off) & 0xFF
        l.append( chr(b) )
        x = x | (b << off)
        off += 8
    l.reverse()
    return six.b(''.join(l))
```
https://github.com/cocagne/pysrp/blob/0414166e9dba63c2677414ace2673ccc24208d23/srp/_pysrp.py#L148

Any idea how to make this optional, so I can encode as necessary for the API?

**Comment by cocagne** [comment]
I'm afraid I don't quite understand what you're asking. UTF-8 is a binary
encoding for string content so when a string is encoded with UTF-8 what you
have are raw bytes rather than a string, which is what you want I think.
Can you elaborate on what you're trying to do and where you think it's
going wrong?

Tom

**Comment by cocagne** [comment]
closing due to lack of response
